project_name: cautious
release:
  github:
    owner: fedeztk
    name: kubectl-cautious
builds:
  - id: cautious
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - arm64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    binary: cautious
    ldflags:
      - -s -w 
      # - -X github.com/fedeztk/kubectl-cautious/pkg/version.version={{ .Version }}
      # - -X github.com/fedeztk/kubectl-cautious/pkg/version.commit={{ .Commit }}
archives:
  - id: cautious
    builds:
    - cautious
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
