apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cautious
spec:
  shortDescription: Cautiously operate inside clusters
  homepage: https://github.com/fedeztk/kubectl-cautious
  description: |
    Cautiously run kubectl commands, no more accidental deletions!
    Supports regexes and is configured via a yaml file under ~/.kube
  version: {{.TagName}}
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    {{addURIAndSha "https://github.com/fedeztk/kubectl-cautious/archive/{{ .TagName }}.tar.gz" .TagName }}
    bin: kubectl-cautious

  - selector:
      matchLabels:
        os: windows
    {{addURIAndSha "https://github.com/fedeztk/kubectl-cautious/archive/{{ .TagName }}.tar.gz" .TagName }}
    bin: "cautious.exe"
