name: Go CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.22.5

      - name: Verify dependencies
        run: go mod verify

      - name: Run go build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...
